services:
  mysql:
    image: "mysql:8.0"
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_DATABASE: demo_db
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
    healthcheck:
      test: [ 'CMD-SHELL', 'mysqladmin ping -h localhost' ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: {}
